# ty: All checks passed!
# basedpyright: 0 errors, 0 warnings, 0 notes
# mypy: Found 2 errors in 1 file (checked 117 source files)

[type_errors.ty]
total_errors = 0

[type_errors.ty.by_type]

[type_errors.ty.by_file]

[type_errors.basedpyright]
total_errors = 0

[type_errors.basedpyright.by_type]

[type_errors.basedpyright.by_file]

[type_errors.mypy]
total_errors = 2

[type_errors.mypy.by_type]
"assignment" = 2

[type_errors.mypy.by_file]
"tests/unit/json_serialize/test_json_serialize.py" = 2
